### ISSUE TITLE
How to crop & align face images?

### ISSUE THREAD

**Issue by yts-tc** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#1]
Now I'm trying your code according to"How to implement our models on your data", but I don't know how to get cropped & aligned face images.
Could you tell me how to crop & align face images? 
And if possible, could you share some samples of cropped & aligned face images?

Thanks,

**Comment by wtomin** [comment]
I will recommend the [OpenFace 2.2.0 toolkit](https://github.com/TadasBaltrusaitis/OpenFace) to you to crop and align faces.

**Comment by yts-tc** [comment]
Thank you for reply. I try it.
