### ISSUE TITLE
AssertionError: The OpenFace output directory should not be empty: examples/utterance_1_opface

### ISSUE THREAD

**Issue by HEzelda** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#16]
Thank you so much for your sharing.
I have a question about running run_example.py.
When I tried to run it , the following error occurs:
      Traceback (most recent call last):
      File "/home/Multitask-Emotion/api/run_example.py", line 20, in <module>
      api.run(example_video, csv_output='examples/utterance_1_opface.csv')
     File "/home/Multitask-Emotion/api/Emotion_API.py", line 111, in run
     assert len(os.listdir(opface_output_dir)) >0 , "The OpenFace output directory should not be empty: {}".format(opface_output_dir)
     AssertionError: The OpenFace output directory should not be empty: examples/utterance_1_opface
Could you tell me how to solve it? Thank you very much!

**Comment by wtomin** [comment]
Can you make sure that your OpenFace has been proper installed and can be executed correctly? I recommend you to read this [wiki](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments) page of OpenFace and run some example like:

`FeatureExtraction -f "C:\my videos\video1.avi"` if it is running on linux.
`FeatureExtraction.exe -f "C:\my videos\video1.avi"` if it is running on Windows.

If the outputs are as expected, then the OpenFace should be properly installed.
