### ISSUE TITLE
关于注释文件

### ISSUE THREAD

**Issue by hust-stone** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#19]
您好，我不确定我的理解是否准确。在./create_annotation_file/Aff_wild2/create_test_set_file.py文件中，您读入了三个关于测试数据集（../cropped_aligned）信息的txt文件（aus_test_set.txt，expression_test_set.txt，va_test_set.txt），据此请问这三个txt文件您是怎样得到的，我应该怎样获得？

**Comment by wtomin** [comment]
这三个文件是[FG2020 ABAW Challenge](https://ibug.doc.ic.ac.uk/resources/fg-2020-competition-affective-behavior-analysis/)的组织者在比赛进行到后期时，给每一个参赛队伍发送的test set file names，以便各位参赛者可以提交test set submission.

如果你想要得到这三个文档，我建议你通过邮箱联络[d.kollias@qmul.ac.uk](mailto:dimitrios.kollias15@imperial.ac.uk)。

**Comment by HEzelda** [comment]
您好，请问您获取到这三个文件了吗，我联系了这个邮箱一直没有回复。
