### ISSUE TITLE
Cannot find txt files (AU.txt, EXPR.txt, and VA.txt)

### ISSUE THREAD

**Issue by richard-bmc** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#22]
I want to test on my own video, so I tried emotion_demo.py, and modifid the content of video_file. But I cannot find the three text files: AU.txt, EXPR.txt, and VA.txt. Where can I find or download them?

**Comment by veb7vmehra** [comment]
Hey @richard-bmc I am facing the same problem, can you tell me how you fixed it?
