### ISSUE TITLE
model file problem in Multitask-CNN-RNN

### ISSUE THREAD

**Issue by ShiZiqiang** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#5]
In multitask-CNN-RNN training step, a resnet50_GRU model is needed. However in models directory, there is only resnet50 model. Could you help to fix the problem?

**Comment by wtomin** [comment]
I uploaded the correct resnet50.py to Multitask-CNN-RNN/models/. Please take a look.

**Comment by ShiZiqiang** [comment]
Thank you so much.
