### ISSUE TITLE
crop and align face images

### ISSUE THREAD

**Issue by ycyoon** [wtomin/Multitask-Emotion-Recognition-with-Incomplete-Labels#7]
Hi, as far as I know, it's not possible to download crop and align face images now.
Could you provide sample crop and align files for reference?

**Comment by wtomin** [comment]
Just check. Did you send emails to the author of Aff-wild2 dataset asking for access to the cropped & aligned faces?

**Comment by ycyoon** [comment]
> Just check. Did you send emails to the author of Aff-wild2 dataset asking for access to the cropped & aligned faces?

No, I didn't because it looks like that the data is only provided for the task participants.

**Comment by wtomin** [comment]
I think the author will be pleasant to provide you the data as long as it is for academic use. Try asking him to give you EULA(End-user license agreement).

**Comment by ycyoon** [comment]
> I think the author will be pleasant to provide you the data as long as it is for academic use. Try asking him to give you EULA(End-user license agreement).

Thank you. I got the data by emailing the author.
